# fly.toml app configuration file generated for portfolio-pal on 2023-06-20T01:52:50+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portfolio-pal"
primary_region = "sin"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
